# Generated by Django 5.0 on 2024-03-20 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_service_uptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('scloud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.scloud')),
            ],
            bases=('services.scloud',),
        ),
    ]
